name: visualea_dev
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
  # list here manually conda-only deps (listed in [tool.conda.environment] section of pyproject)
  - python
  - pip
  - qtconsole
  - QtPy
  - openalea.core
  - openalea.scipack
  - openalea.oalab
  - openalea.grapheditor
  # let pip install the rest using pyproject.toml (if you are okay with conda/pip mix)
  - pip:
      - -e .."[doc, test]"
