name: visualea2
channels:
  - openalea3
  - conda-forge
dependencies:
  # list here manually conda-only deps (listed in [tool.conda.environment] section of pyproject)
  - python
  - pip
  - qtconsole
  - QtPy
  - openalea.core
  - openalea.oalab
  - openalea.grapheditor
  - openalea.stdlib
  # let pip install the rest using pyproject.toml (if you are okay with conda/pip mix)
  - pip:
      - -e .."[doc, test]"
