# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ioconfig.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IOConfig(object):
    def setupUi(self, IOConfig):
        IOConfig.setObjectName("IOConfig")
        IOConfig.resize(444, 441)
        self.vboxlayout = QtWidgets.QVBoxLayout(IOConfig)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtWidgets.QLabel(IOConfig)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.inTable = QtWidgets.QTableView(IOConfig)
        self.inTable.setObjectName("inTable")
        self.vboxlayout.addWidget(self.inTable)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.addInput = QtWidgets.QPushButton(IOConfig)
        self.addInput.setObjectName("addInput")
        self.hboxlayout.addWidget(self.addInput)
        self.delInput = QtWidgets.QPushButton(IOConfig)
        self.delInput.setObjectName("delInput")
        self.hboxlayout.addWidget(self.delInput)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.label_2 = QtWidgets.QLabel(IOConfig)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.outTable = QtWidgets.QTableView(IOConfig)
        self.outTable.setObjectName("outTable")
        self.vboxlayout.addWidget(self.outTable)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.addOutput = QtWidgets.QPushButton(IOConfig)
        self.addOutput.setObjectName("addOutput")
        self.hboxlayout1.addWidget(self.addOutput)
        self.delOutput = QtWidgets.QPushButton(IOConfig)
        self.delOutput.setObjectName("delOutput")
        self.hboxlayout1.addWidget(self.delOutput)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.buttonBox = QtWidgets.QDialogButtonBox(IOConfig)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(IOConfig)
        self.buttonBox.accepted.connect(IOConfig.accept)
        self.buttonBox.rejected.connect(IOConfig.reject)
        QtCore.QMetaObject.connectSlotsByName(IOConfig)
        IOConfig.setTabOrder(self.inTable, self.addInput)
        IOConfig.setTabOrder(self.addInput, self.delInput)
        IOConfig.setTabOrder(self.delInput, self.outTable)
        IOConfig.setTabOrder(self.outTable, self.addOutput)
        IOConfig.setTabOrder(self.addOutput, self.delOutput)
        IOConfig.setTabOrder(self.delOutput, self.buttonBox)

    def retranslateUi(self, IOConfig):
        _translate = QtCore.QCoreApplication.translate
        IOConfig.setWindowTitle(_translate("IOConfig", "I/O Configuration"))
        self.label.setText(_translate("IOConfig", "Inputs"))
        self.addInput.setText(_translate("IOConfig", "+"))
        self.delInput.setText(_translate("IOConfig", "-"))
        self.label_2.setText(_translate("IOConfig", "Outputs"))
        self.addOutput.setText(_translate("IOConfig", "+"))
        self.delOutput.setText(_translate("IOConfig", "-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IOConfig = QtWidgets.QDialog()
    ui = Ui_IOConfig()
    ui.setupUi(IOConfig)
    IOConfig.show()
    sys.exit(app.exec_())
