# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listedit.ui'
#
# Created by: PyQt4 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ListEdit(object):
    def setupUi(self, ListEdit):
        ListEdit.setObjectName("ListEdit")
        ListEdit.resize(400, 300)
        self.vboxlayout = QtWidgets.QVBoxLayout(ListEdit)
        self.vboxlayout.setObjectName("vboxlayout")
        self.listWidget = QtWidgets.QListWidget(ListEdit)
        self.listWidget.setObjectName("listWidget")
        self.vboxlayout.addWidget(self.listWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(ListEdit)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(ListEdit)
        self.buttonBox.accepted.connect(ListEdit.accept)
        self.buttonBox.rejected.connect(ListEdit.reject)
        QtCore.QMetaObject.connectSlotsByName(ListEdit)

    def retranslateUi(self, ListEdit):
        _translate = QtCore.QCoreApplication.translate
        ListEdit.setWindowTitle(_translate("ListEdit", "Dialog"))
