# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newdata.ui'
#
# Created by: PyQt4 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewDataDialog(object):
    def setupUi(self, NewDataDialog):
        NewDataDialog.setObjectName("NewDataDialog")
        NewDataDialog.resize(444, 169)
        self.gridlayout = QtWidgets.QGridLayout(NewDataDialog)
        self.gridlayout.setObjectName("gridlayout")
        self.label = QtWidgets.QLabel(NewDataDialog)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.packageBox = QtWidgets.QComboBox(NewDataDialog)
        self.packageBox.setObjectName("packageBox")
        self.gridlayout.addWidget(self.packageBox, 0, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(NewDataDialog)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(NewDataDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridlayout.addWidget(self.nameEdit, 1, 1, 1, 1)
        self.browseButton = QtWidgets.QPushButton(NewDataDialog)
        self.browseButton.setObjectName("browseButton")
        self.gridlayout.addWidget(self.browseButton, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(NewDataDialog)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.descriptionEdit = QtWidgets.QLineEdit(NewDataDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridlayout.addWidget(self.descriptionEdit, 2, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(NewDataDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridlayout.addWidget(self.buttonBox, 3, 0, 1, 3)

        self.retranslateUi(NewDataDialog)
        self.buttonBox.accepted.connect(NewDataDialog.accept)
        self.buttonBox.rejected.connect(NewDataDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewDataDialog)
        NewDataDialog.setTabOrder(self.packageBox, self.nameEdit)
        NewDataDialog.setTabOrder(self.nameEdit, self.descriptionEdit)
        NewDataDialog.setTabOrder(self.descriptionEdit, self.buttonBox)

    def retranslateUi(self, NewDataDialog):
        _translate = QtCore.QCoreApplication.translate
        NewDataDialog.setWindowTitle(_translate("NewDataDialog", "Import data"))
        self.label.setText(_translate("NewDataDialog", "Package"))
        self.label_2.setText(_translate("NewDataDialog", "File"))
        self.browseButton.setText(_translate("NewDataDialog", "..."))
        self.label_4.setText(_translate("NewDataDialog", "Description"))
