# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newgraph.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewGraphDialog(object):
    def setupUi(self, NewGraphDialog):
        NewGraphDialog.setObjectName("NewGraphDialog")
        NewGraphDialog.resize(424, 326)
        NewGraphDialog.setWindowTitle("")
        self.gridlayout = QtWidgets.QGridLayout(NewGraphDialog)
        self.gridlayout.setContentsMargins(9, 9, 9, 9)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(NewGraphDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridlayout.addWidget(self.buttonBox, 5, 0, 1, 4)
        self.nameEdit = QtWidgets.QLineEdit(NewGraphDialog)
        self.nameEdit.setObjectName("nameEdit")
        self.gridlayout.addWidget(self.nameEdit, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(NewGraphDialog)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.descriptionEdit = QtWidgets.QLineEdit(NewGraphDialog)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridlayout.addWidget(self.descriptionEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(NewGraphDialog)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(NewGraphDialog)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label, 0, 0, 1, 1)
        self.packageBox = QtWidgets.QComboBox(NewGraphDialog)
        self.packageBox.setObjectName("packageBox")
        self.gridlayout.addWidget(self.packageBox, 0, 1, 1, 1)
        self.categoryEdit = QtWidgets.QComboBox(NewGraphDialog)
        self.categoryEdit.setEditable(True)
        self.categoryEdit.setObjectName("categoryEdit")
        self.gridlayout.addWidget(self.categoryEdit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(NewGraphDialog)
        self.label_4.setObjectName("label_4")
        self.gridlayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.ioButton = QtWidgets.QPushButton(NewGraphDialog)
        self.ioButton.setObjectName("ioButton")
        self.gridlayout.addWidget(self.ioButton, 4, 1, 1, 1)

        self.retranslateUi(NewGraphDialog)
        self.buttonBox.accepted.connect(NewGraphDialog.accept)
        self.buttonBox.rejected.connect(NewGraphDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(NewGraphDialog)
        NewGraphDialog.setTabOrder(self.packageBox, self.nameEdit)
        NewGraphDialog.setTabOrder(self.nameEdit, self.categoryEdit)
        NewGraphDialog.setTabOrder(self.categoryEdit, self.descriptionEdit)
        NewGraphDialog.setTabOrder(self.descriptionEdit, self.ioButton)
        NewGraphDialog.setTabOrder(self.ioButton, self.buttonBox)

    def retranslateUi(self, NewGraphDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label_2.setText(_translate("NewGraphDialog", "Name"))
        self.label_3.setText(_translate("NewGraphDialog", "Category"))
        self.label.setText(_translate("NewGraphDialog", "Package"))
        self.label_4.setText(_translate("NewGraphDialog", "Description"))
        self.ioButton.setText(_translate("NewGraphDialog", "Inputs / Outputs"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewGraphDialog = QtWidgets.QDialog()
    ui = Ui_NewGraphDialog()
    ui.setupUi(NewGraphDialog)
    NewGraphDialog.show()
    sys.exit(app.exec_())
