# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nodechooser.ui'
#
# Created by: PyQt4 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NodeChooser(object):
    def setupUi(self, NodeChooser):
        NodeChooser.setObjectName("NodeChooser")
        NodeChooser.resize(417, 156)
        self.vboxlayout = QtWidgets.QVBoxLayout(NodeChooser)
        self.vboxlayout.setObjectName("vboxlayout")
        self.comboBox = QtWidgets.QComboBox(NodeChooser)
        self.comboBox.setEditable(True)
        self.comboBox.setObjectName("comboBox")
        self.vboxlayout.addWidget(self.comboBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(NodeChooser)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(NodeChooser)
        self.buttonBox.accepted.connect(NodeChooser.accept)
        self.buttonBox.rejected.connect(NodeChooser.reject)
        QtCore.QMetaObject.connectSlotsByName(NodeChooser)

    def retranslateUi(self, NodeChooser):
        _translate = QtCore.QCoreApplication.translate
        NodeChooser.setWindowTitle(_translate("NodeChooser", "Choose a node"))
