# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tofactory.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FactorySelector(object):
    def setupUi(self, FactorySelector):
        FactorySelector.setObjectName("FactorySelector")
        FactorySelector.resize(371, 143)
        icon = QtGui.QIcon()
        icon.addFile(":/icons/diagram.png")
        FactorySelector.setWindowIcon(icon)
        self.vboxlayout = QtWidgets.QVBoxLayout(FactorySelector)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.label = QtWidgets.QLabel(FactorySelector)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.hboxlayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(FactorySelector)
        self.comboBox.setObjectName("comboBox")
        self.hboxlayout.addWidget(self.comboBox)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.label_2 = QtWidgets.QLabel(FactorySelector)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label_3 = QtWidgets.QLabel(FactorySelector)
        self.label_3.setObjectName("label_3")
        self.hboxlayout1.addWidget(self.label_3)
        self.newFactoryButton = QtWidgets.QPushButton(FactorySelector)
        self.newFactoryButton.setObjectName("newFactoryButton")
        self.hboxlayout1.addWidget(self.newFactoryButton)
        self.vboxlayout.addLayout(self.hboxlayout1)
        self.buttonBox = QtWidgets.QDialogButtonBox(FactorySelector)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(FactorySelector)
        self.buttonBox.accepted.connect(FactorySelector.accept)
        self.buttonBox.rejected.connect(FactorySelector.reject)
        QtCore.QMetaObject.connectSlotsByName(FactorySelector)
        FactorySelector.setTabOrder(self.comboBox, self.newFactoryButton)
        FactorySelector.setTabOrder(self.newFactoryButton, self.buttonBox)

    def retranslateUi(self, FactorySelector):
        _translate = QtCore.QCoreApplication.translate
        FactorySelector.setWindowTitle(_translate("FactorySelector", "Selector"))
        self.label.setText(_translate("FactorySelector", "Select a Composite Node :"))
        self.label_2.setText(_translate("FactorySelector", "Or"))
        self.label_3.setText(_translate("FactorySelector", "Create a new Composite Node"))
        self.newFactoryButton.setText(_translate("FactorySelector", "New"))
from openalea.visualea import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FactorySelector = QtWidgets.QDialog()
    ui = Ui_FactorySelector()
    ui.setupUi(FactorySelector)
    FactorySelector.show()
    sys.exit(app.exec_())
