# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableedit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableEditor(object):
    def setupUi(self, TableEditor):
        TableEditor.setObjectName("TableEditor")
        TableEditor.resize(261, 300)
        self.vboxlayout = QtWidgets.QVBoxLayout(TableEditor)
        self.vboxlayout.setContentsMargins(9, 9, 9, 9)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setObjectName("vboxlayout")
        self.tableWidget = QtWidgets.QTableWidget(TableEditor)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.vboxlayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(TableEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vboxlayout.addWidget(self.buttonBox)

        self.retranslateUi(TableEditor)
        self.buttonBox.accepted.connect(TableEditor.accept)
        self.buttonBox.rejected.connect(TableEditor.reject)
        QtCore.QMetaObject.connectSlotsByName(TableEditor)

    def retranslateUi(self, TableEditor):
        _translate = QtCore.QCoreApplication.translate
        TableEditor.setWindowTitle(_translate("TableEditor", "Internals"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("TableEditor", "Key"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("TableEditor", "Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TableEditor = QtWidgets.QDialog()
    ui = Ui_TableEditor()
    ui.setupUi(TableEditor)
    TableEditor.show()
    sys.exit(app.exec_())
